version: 2.1

parameters:
  default-node-image:
    type: string
    default: "cimg/node:25.9"
  target:
    type: enum
    enum: [none, do-release]
    default: none
  release:
    type: string
    default: "0.0.1"

commands:
  init-dependencies:
    steps:
      - run:
          name: "Install Dependencies"
          command: npm install

jobs:
  tests:
    docker:
      - image: << pipeline.parameters.default-node-image  >>
    steps:
      - checkout
      - init-dependencies
      - run:
          name: Vanilla Tests
          command: |
            npm run test
  release:
    docker:
      - image: << pipeline.parameters.default-node-image  >>
    steps:
      - checkout
      - run:
          name: Verify Envars
          command: |
            echo From config.yml SUPER_SECRET=\"$SUPER_SECRET\"
            echo Release value << pipeline.git.tag >>
      - run:
          name: Release Script
          command: |
            ./scripts/on-release.sh

release_filter: &release_filter
  filters:
    tags:
      only:
        - /.*test/
        - /^v[0-9]+(\.[0-9]+){2}(-(rc|beta)[0-9]+)?/
    branches:
      only:
        - master

when_experim: &when_experim
  when:
    and:
      - equal: [ master, << pipeline.git.branch>> ]
      - equal: [ do-release, << pipeline.parameters.target >> ]

workflows:
  build:
    jobs:
      - tests
  release:
    jobs:
      - tests
      - release:
        <<: *release_filter
