version: 2.1

parameters:
  default-node-image:
    type: string
    default: "cimg/node:25.9"

commands:
  init-dependencies:
    steps:
      - run:
          name: "Install Dependencies"
          command: npm install

jobs:
  tests:
    docker:
      - image: << pipeline.parameters.default-node-image  >>
    steps:
      - checkout
      - init-dependencies
      - run:
          name: Vanilla Tests
          command: |
            npm run test
  release:
    docker:
      - image: << pipeline.parameters.default-node-image  >>
    steps:
      - checkout
      - run:
          name: Release Script
          command: |
            ./scripts/on-release.sh

workflows:
  build:
    jobs:
      - tests
  release:
    jobs:
      - tests
      - release
